// Regma IT job pack — imported into the jobs table via the admin
// dashboard ("Import job pack" button). Loaded only by admin.html.
const REGMA_JOB_PACK = [
 {
  "title": "Test Engineer — Automotive",
  "department": "Testing & Verification",
  "type": "Full-time",
  "location": "Gothenburg",
  "salary": "",
  "summary": "Plan and run vehicle tests for active safety systems — in the lab, on the test track, and on public roads.",
  "responsibilities": "Prepare and execute in-vehicle tests of active safety functions\nAnalyse logs and document test results clearly\nSupport function owners and developers with findings from testing\nMaintain test equipment and measurement setups",
  "requirements": "BSc/MSc in a relevant engineering field or equivalent\nExperience with Vector tools such as CANalyzer and vehicle diagnostic tooling\nSwedish B driving licence and solid driving experience\nFluent English in speech and writing; Swedish is a strong plus\nBased in or able to commute to the Gothenburg area",
  "nice_to_have": "Python or Matlab skills\nTest track driving permit (e.g. Hällered T2)\nC/CE driving licence",
  "is_open": true
 },
 {
  "title": "Maintenance Engineer — Mechanical",
  "department": "Engineering",
  "type": "Full-time",
  "location": "Gothenburg",
  "salary": "",
  "summary": "Secure the reliability and maintainability of new production equipment — from design review to preventive maintenance plans.",
  "responsibilities": "Work with equipment suppliers to meet reliability & maintainability standards\nParticipate in concept and design reviews against R&M specifications\nPerform mechanical inspections at delivery acceptance\nPrepare spare-part strategies and preventive maintenance plans\nOwn the quality and completeness of maintenance documentation",
  "requirements": "Strong knowledge of maintenance practices and processes\nExperience with mechanical engineering in industrial projects\nExperience setting up preventive maintenance plans and spare part engineering\nFluent English in speech and writing; Swedish is a strong plus\nBased in or able to commute to the Gothenburg area",
  "nice_to_have": "",
  "is_open": true
 },
 {
  "title": "System Design Leader",
  "department": "Engineering",
  "type": "Full-time",
  "location": "Gothenburg",
  "salary": "",
  "summary": "Lead system design in the early phases of powertrain development — requirements, concept evaluation, and design specification.",
  "responsibilities": "Lead and coordinate system design activities in early development phases\nManage attribute, functional and cross-system requirements\nDrive concept evaluation and system design specification work\nParticipate in supplier negotiations on software requirements\nBuild the technology road map across projects",
  "requirements": "Solid systems engineering background in automotive or similar industry\nStrong requirement management and concept evaluation experience\nComfortable leading cross-functional work, occasionally with travel\nFluent English in speech and writing; Swedish is a strong plus\nBased in or able to commute to the Gothenburg area",
  "nice_to_have": "",
  "is_open": true
 },
 {
  "title": "Senior Digital Product Designer",
  "department": "Design",
  "type": "Full-time",
  "location": "Gothenburg",
  "salary": "",
  "summary": "Design in-car digital experiences end-to-end — from concepts and user flows to production-ready UI for a modern vehicle ecosystem.",
  "responsibilities": "Own the holistic in-car digital experience across touchpoints\nTranslate complex feature requests into intuitive user flows\nCreate wireframes, prototypes and production-ready designs\nDrive design discussions with stakeholders and engineers\nSafeguard quality and consistency across the design process",
  "requirements": "Strong UX and visual design craft with a diverse portfolio\nExperience with design systems and implementation specs\nSkilled at detailed UI animation and interaction design\nFluent English in speech and writing; Swedish is a strong plus\nBased in or able to commute to the Gothenburg area",
  "nice_to_have": "",
  "is_open": true
 },
 {
  "title": "Chief Exterior Designer — Concept & Vehicle Architecture",
  "department": "Design",
  "type": "Full-time",
  "location": "Gothenburg",
  "salary": "",
  "summary": "Lead early-phase exterior design and vehicle architecture for future vehicle programs, guiding an on-site design team.",
  "responsibilities": "Lead exterior ideation for advanced and production programs\nDevelop proportions, form language and concept directions\nAlign design intent with engineering, platform and packaging constraints\nGuide and mentor the on-site exterior design team\nPresent to senior management across international studios",
  "requirements": "20+ years of automotive design experience including exterior design\nDeep understanding of vehicle architecture, BIW and packaging\nExperienced presenter, comfortable in cross-cultural settings with travel\nFluent English in speech and writing; Swedish is a strong plus\nBased in or able to commute to the Gothenburg area",
  "nice_to_have": "",
  "is_open": true
 },
 {
  "title": "CRM Developer — Dynamics 365 (Senior)",
  "department": "Software & IT",
  "type": "Full-time",
  "location": "Gothenburg",
  "salary": "",
  "summary": "Build and integrate a global Microsoft Dynamics 365 CE Sales platform — plugins, workflows, integrations and CI/CD.",
  "responsibilities": "Develop and maintain Dynamics 365 CE Sales customisations and plugins\nBuild integrations using Azure Function Apps, Service Bus and Storage\nMaintain CI/CD pipelines in Azure DevOps\nWork hands-on in an agile, cross-functional product team",
  "requirements": "5–8 years of relevant experience\n8+ years developing on Microsoft Dynamics 365 CE\nStrong .NET, C# and JavaScript/TypeScript skills\nExperience with Azure services and CI/CD pipelines\nFluent English in speech and writing; Swedish is a strong plus\nBased in or able to commute to the Gothenburg area",
  "nice_to_have": "Kafka, Snowflake, MS SQL or WSO2 experience",
  "is_open": true
 },
 {
  "title": "Agile Flow Leader (Senior)",
  "department": "Management & Ops",
  "type": "Full-time",
  "location": "Gothenburg",
  "salary": "",
  "summary": "Coach teams and improve flow in an agile product organisation — facilitating ceremonies, removing blockers and building continuous improvement.",
  "responsibilities": "Facilitate agile ceremonies and support product teams day to day\nVisualise and improve flow of work across teams\nCoach team members and leaders in agile ways of working\nRemove impediments and escalate systemic blockers",
  "requirements": "5–8 years of relevant experience\nSeveral years as Scrum Master, Agile Coach or Flow Leader\nStrong facilitation and coaching skills\nExperience with agile at scale in larger organisations\nFluent English in speech and writing; Swedish is a strong plus\nBased in or able to commute to the Gothenburg area",
  "nice_to_have": "",
  "is_open": true
 },
 {
  "title": "IT Service Manager (Senior)",
  "department": "Software & IT",
  "type": "Full-time",
  "location": "Gothenburg",
  "salary": "",
  "summary": "Own the quality, availability and continuous improvement of business-critical IT services in a large enterprise environment.",
  "responsibilities": "Manage the lifecycle and quality of assigned IT services\nCoordinate suppliers, support teams and stakeholders\nDrive incident, problem and change management routines\nTrack service KPIs and lead continuous improvement",
  "requirements": "5–8 years of relevant experience\nSolid ITSM/ITIL experience in enterprise environments\nStrong stakeholder and supplier management skills\nStructured, communicative and delivery-focused\nFluent English in speech and writing; Swedish is a strong plus\nBased in or able to commute to the Gothenburg area",
  "nice_to_have": "",
  "is_open": true
 },
 {
  "title": "Product Quality Assurance Manager (Lead)",
  "department": "Quality",
  "type": "Full-time",
  "location": "Gothenburg",
  "salary": "",
  "summary": "Lead product quality assurance across development projects — setting the standards, audits and follow-up that keep quality on track.",
  "responsibilities": "Define and follow up product quality targets in projects\nLead quality reviews, audits and root-cause investigations\nCoach project teams in quality methods and standards\nReport quality status to senior stakeholders",
  "requirements": "8+ years of experience, including leading teams or workstreams\nStrong background in product quality within manufacturing or automotive\nExperience with quality tools (8D, FMEA, root-cause analysis)\nConfident communicator across all organisational levels\nFluent English in speech and writing; Swedish is a strong plus\nBased in or able to commute to the Gothenburg area",
  "nice_to_have": "",
  "is_open": true
 },
 {
  "title": "System Verification Engineer (Senior Expert)",
  "department": "Testing & Verification",
  "type": "Full-time",
  "location": "Gothenburg",
  "salary": "",
  "summary": "Verify complete systems against requirements — planning, executing and documenting tests at rig and vehicle level.",
  "responsibilities": "Plan and execute system-level verification activities\nDesign test cases from system requirements\nRun tests in rigs, HIL environments and complete vehicles\nAnalyse results and report deviations to development teams",
  "requirements": "8+ years of deep experience in the field\nExperience with system verification in automotive or embedded products\nComfortable with measurement tools, logging and analysis\nGood understanding of requirements-based testing\nFluent English in speech and writing; Swedish is a strong plus\nBased in or able to commute to the Gothenburg area",
  "nice_to_have": "",
  "is_open": true
 },
 {
  "title": "Electrical & Electronics Hardware Engineer (Senior)",
  "department": "Engineering",
  "type": "Full-time",
  "location": "Gothenburg",
  "salary": "",
  "summary": "Develop electrical and electronic hardware for demanding vehicle applications — from schematics to validated components.",
  "responsibilities": "Design and specify E/E hardware components and interfaces\nWork with suppliers on component development and validation\nSupport integration, troubleshooting and root-cause work\nDocument designs and requirements",
  "requirements": "5–8 years of relevant experience\nSolid E/E hardware engineering background\nExperience with automotive electronics and validation\nFamiliar with schematics, wiring and EMC considerations\nFluent English in speech and writing; Swedish is a strong plus\nBased in or able to commute to the Gothenburg area",
  "nice_to_have": "",
  "is_open": true
 },
 {
  "title": "Maintenance Engineer (Senior)",
  "department": "Engineering",
  "type": "Full-time",
  "location": "Gothenburg",
  "salary": "",
  "summary": "Keep production equipment reliable and available — preventive maintenance, improvements and technical support to operations.",
  "responsibilities": "Develop and maintain preventive maintenance programs\nAnalyse equipment performance and reduce recurring downtime\nSupport operations with technical troubleshooting\nManage spare parts and maintenance documentation",
  "requirements": "5–8 years of relevant experience\nExperience in industrial maintenance engineering\nGood knowledge of maintenance processes and systems\nPractical, structured and improvement-driven\nFluent English in speech and writing; Swedish is a strong plus\nBased in or able to commute to the Gothenburg area",
  "nice_to_have": "",
  "is_open": true
 },
 {
  "title": "Production Capacity Planner (Lead)",
  "department": "Management & Ops",
  "type": "Full-time",
  "location": "Gothenburg",
  "salary": "",
  "summary": "Plan and balance production capacity — turning demand forecasts into achievable production programs.",
  "responsibilities": "Translate demand forecasts into capacity and production plans\nIdentify bottlenecks and support capacity investment decisions\nCoordinate with manufacturing, logistics and purchasing\nMaintain planning parameters and scenarios",
  "requirements": "8+ years of experience, including leading teams or workstreams\nExperience in production or capacity planning in manufacturing\nStrong analytical skills, comfortable with planning systems\nClear communicator between operations and management\nFluent English in speech and writing; Swedish is a strong plus\nBased in or able to commute to the Gothenburg area",
  "nice_to_have": "",
  "is_open": true
 },
 {
  "title": "Strategic Buyer (Senior)",
  "department": "Purchasing",
  "type": "Full-time",
  "location": "Gothenburg",
  "salary": "",
  "summary": "Own supplier strategy for your category — sourcing, negotiating and developing suppliers for long-term value.",
  "responsibilities": "Develop and execute category and supplier strategies\nLead sourcing events, negotiations and contract work\nMonitor supplier performance and drive improvements\nWork cross-functionally with engineering and quality",
  "requirements": "5–8 years of relevant experience\nSeveral years of strategic purchasing experience\nStrong negotiation and analytical skills\nExperience in industrial or automotive sourcing\nFluent English in speech and writing; Swedish is a strong plus\nBased in or able to commute to the Gothenburg area",
  "nice_to_have": "",
  "is_open": true
 },
 {
  "title": "Test Rig Maintenance Technician (Specialist)",
  "department": "Testing & Verification",
  "type": "Full-time",
  "location": "Gothenburg",
  "salary": "",
  "summary": "Keep advanced test rigs running — maintenance, calibration and hands-on improvement of the test environment.",
  "responsibilities": "Perform preventive and corrective maintenance on test rigs\nCalibrate instrumentation and measurement chains\nSupport test engineers with rig adaptations and fixtures\nKeep rig documentation and spare parts in order",
  "requirements": "5+ years of relevant experience in the field\nHands-on technical background (mechatronics, electrical or similar)\nExperience maintaining test or production equipment\nSafety-minded, methodical and service-oriented\nFluent English in speech and writing; Swedish is a strong plus\nBased in or able to commute to the Gothenburg area",
  "nice_to_have": "",
  "is_open": true
 },
 {
  "title": "Feature Leader (Specialist)",
  "department": "Management & Ops",
  "type": "Full-time",
  "location": "Gothenburg",
  "salary": "",
  "summary": "Drive a product feature from concept to delivery — coordinating engineering teams and keeping scope, time and quality together.",
  "responsibilities": "Own the delivery of assigned product features end-to-end\nCoordinate development teams and resolve cross-team dependencies\nTrack progress, risks and quality toward feature milestones\nReport status to project and product management",
  "requirements": "5+ years of relevant experience in the field\nExperience leading technical deliveries in complex products\nStrong coordination and communication skills\nAutomotive or embedded product background is a plus\nFluent English in speech and writing; Swedish is a strong plus\nBased in or able to commute to the Gothenburg area",
  "nice_to_have": "",
  "is_open": true
 },
 {
  "title": "Mechanical Engineer (Senior Expert)",
  "department": "Engineering",
  "type": "Full-time",
  "location": "Gothenburg",
  "salary": "",
  "summary": "Design and develop mechanical solutions for demanding industrial products — from concept and CAD to verified parts.",
  "responsibilities": "Design mechanical parts and assemblies in 3D CAD\nPerform tolerance analysis and design verification\nCollaborate with suppliers on manufacturability\nSupport prototype builds and testing",
  "requirements": "8+ years of deep experience in the field\nSolid mechanical design background\nProficiency in a major CAD system (Catia, Creo or similar)\nUnderstanding of manufacturing methods and materials\nFluent English in speech and writing; Swedish is a strong plus\nBased in or able to commute to the Gothenburg area",
  "nice_to_have": "",
  "is_open": true
 },
 {
  "title": "Embedded Software Integration Engineer (Specialist)",
  "department": "Software & IT",
  "type": "Full-time",
  "location": "Gothenburg",
  "salary": "",
  "summary": "Integrate embedded software into complete ECUs and vehicles — builds, configuration and making all the pieces work together.",
  "responsibilities": "Integrate software components into ECU platforms\nManage build chains, configurations and releases\nDebug integration issues across software and hardware\nWork closely with application and platform teams",
  "requirements": "5+ years of relevant experience in the field\nExperience with embedded software integration (C, AUTOSAR or similar)\nComfortable with build systems, scripting and CI environments\nStructured troubleshooting mindset\nFluent English in speech and writing; Swedish is a strong plus\nBased in or able to commute to the Gothenburg area",
  "nice_to_have": "",
  "is_open": true
 },
 {
  "title": "Embedded Software Application Engineer (Specialist)",
  "department": "Software & IT",
  "type": "Full-time",
  "location": "Gothenburg",
  "salary": "",
  "summary": "Develop embedded application software for vehicle functions — from requirements to tested code running in the ECU.",
  "responsibilities": "Design and implement embedded application software in C/C++\nWork with function owners on requirements and behaviour\nTest and debug software in SIL/HIL environments and vehicles\nContribute to code reviews and continuous improvement",
  "requirements": "5+ years of relevant experience in the field\nEmbedded C/C++ development experience\nUnderstanding of automotive software architectures (e.g. AUTOSAR)\nExperience with embedded toolchains and debugging\nFluent English in speech and writing; Swedish is a strong plus\nBased in or able to commute to the Gothenburg area",
  "nice_to_have": "",
  "is_open": true
 },
 {
  "title": "UX Designer (Senior)",
  "department": "Design",
  "type": "Full-time",
  "location": "Gothenburg",
  "salary": "",
  "summary": "Shape user experiences for digital tools and vehicle functions — research, flows, prototypes and polished UI.",
  "responsibilities": "Conduct user research and translate insights into design\nCreate user flows, wireframes and interactive prototypes\nDeliver polished UI aligned with the design system\nWork closely with product owners and developers",
  "requirements": "5–8 years of relevant experience\nStrong UX portfolio across research and UI work\nExpert-level Figma or equivalent design tooling\nExperience working with design systems\nFluent English in speech and writing; Swedish is a strong plus\nBased in or able to commute to the Gothenburg area",
  "nice_to_have": "",
  "is_open": true
 },
 {
  "title": "Price Analyst",
  "department": "Finance",
  "type": "Full-time",
  "location": "Gothenburg",
  "salary": "",
  "summary": "Analyse pricing and cost structures to support commercial decisions — building the models and insight behind the numbers.",
  "responsibilities": "Analyse price, cost and margin development across markets\nBuild and maintain pricing models and dashboards\nSupport commercial teams with pricing recommendations\nPrepare analyses for management decisions",
  "requirements": "3–5 years of relevant experience\nAnalytical background in finance, pricing or controlling\nAdvanced Excel and good BI tooling skills (Power BI or similar)\nBusiness-minded with strong attention to detail\nFluent English in speech and writing; Swedish is a strong plus\nBased in or able to commute to the Gothenburg area",
  "nice_to_have": "",
  "is_open": true
 },
 {
  "title": "System Design Engineer (Senior Expert)",
  "department": "Engineering",
  "type": "Full-time",
  "location": "Gothenburg",
  "salary": "",
  "summary": "Design vehicle systems from requirements to specification — balancing function, cost and integration across the product.",
  "responsibilities": "Break down product requirements into system design\nSpecify interfaces and system behaviour\nEvaluate design concepts against attributes and cost\nSupport integration and verification teams",
  "requirements": "8+ years of deep experience in the field\nSystems engineering experience in automotive or similar\nStrong requirement management skills\nGood understanding of E/E architectures\nFluent English in speech and writing; Swedish is a strong plus\nBased in or able to commute to the Gothenburg area",
  "nice_to_have": "",
  "is_open": true
 },
 {
  "title": "UX Designer (Expert)",
  "department": "Design",
  "type": "Full-time",
  "location": "Gothenburg",
  "salary": "",
  "summary": "Shape user experiences for digital tools and vehicle functions — research, flows, prototypes and polished UI.",
  "responsibilities": "Conduct user research and translate insights into design\nCreate user flows, wireframes and interactive prototypes\nDeliver polished UI aligned with the design system\nWork closely with product owners and developers",
  "requirements": "8+ years of deep experience in the field\nStrong UX portfolio across research and UI work\nExpert-level Figma or equivalent design tooling\nExperience working with design systems\nFluent English in speech and writing; Swedish is a strong plus\nBased in or able to commute to the Gothenburg area",
  "nice_to_have": "",
  "is_open": true
 },
 {
  "title": "System Verification Engineer (Expert)",
  "department": "Testing & Verification",
  "type": "Full-time",
  "location": "Gothenburg",
  "salary": "",
  "summary": "Verify complete systems against requirements — planning, executing and documenting tests at rig and vehicle level.",
  "responsibilities": "Plan and execute system-level verification activities\nDesign test cases from system requirements\nRun tests in rigs, HIL environments and complete vehicles\nAnalyse results and report deviations to development teams",
  "requirements": "8+ years of deep experience in the field\nExperience with system verification in automotive or embedded products\nComfortable with measurement tools, logging and analysis\nGood understanding of requirements-based testing\nFluent English in speech and writing; Swedish is a strong plus\nBased in or able to commute to the Gothenburg area",
  "nice_to_have": "",
  "is_open": true
 },
 {
  "title": "Industrialization Project Manager (Lead)",
  "department": "Management & Ops",
  "type": "Full-time",
  "location": "Gothenburg",
  "salary": "",
  "summary": "Take new products from development into production — planning and driving the industrialisation across plants and suppliers.",
  "responsibilities": "Plan and lead industrialisation activities for new products\nCoordinate manufacturing engineering, quality and logistics\nSecure equipment, tooling and process readiness\nTrack timeline, cost and launch readiness",
  "requirements": "8+ years of experience, including leading teams or workstreams\nProject management experience in manufacturing or industrialisation\nUnderstanding of production processes and launch phases\nStrong cross-functional leadership\nFluent English in speech and writing; Swedish is a strong plus\nBased in or able to commute to the Gothenburg area",
  "nice_to_have": "",
  "is_open": true
 },
 {
  "title": "System Design Engineer (Expert)",
  "department": "Engineering",
  "type": "Full-time",
  "location": "Gothenburg",
  "salary": "",
  "summary": "Design vehicle systems from requirements to specification — balancing function, cost and integration across the product.",
  "responsibilities": "Break down product requirements into system design\nSpecify interfaces and system behaviour\nEvaluate design concepts against attributes and cost\nSupport integration and verification teams",
  "requirements": "8+ years of deep experience in the field\nSystems engineering experience in automotive or similar\nStrong requirement management skills\nGood understanding of E/E architectures\nFluent English in speech and writing; Swedish is a strong plus\nBased in or able to commute to the Gothenburg area",
  "nice_to_have": "",
  "is_open": true
 },
 {
  "title": "Product Development Project Manager (Lead)",
  "department": "Management & Ops",
  "type": "Full-time",
  "location": "Gothenburg",
  "salary": "",
  "summary": "Lead product development projects end-to-end — scope, timeline, budget and a team of engineers moving in the same direction.",
  "responsibilities": "Own project scope, timeline and budget\nLead cross-functional development teams\nManage risks, decisions and stakeholder communication\nReport progress to steering committees",
  "requirements": "8+ years of experience, including leading teams or workstreams\nProven project management experience in product development\nComfortable with gate-based and agile development models\nStrong leadership and communication skills\nFluent English in speech and writing; Swedish is a strong plus\nBased in or able to commute to the Gothenburg area",
  "nice_to_have": "",
  "is_open": true
 },
 {
  "title": "Manufacturing Product Preparation Engineer (Senior)",
  "department": "Engineering",
  "type": "Full-time",
  "location": "Gothenburg",
  "salary": "",
  "summary": "Prepare new products for efficient manufacturing — process design, assembly instructions and producibility feedback to R&D.",
  "responsibilities": "Design assembly processes and line balancing for new products\nCreate work instructions and manufacturing documentation\nGive producibility feedback to design teams\nSupport launches and ramp-up in the plant",
  "requirements": "5–8 years of relevant experience\nManufacturing or production engineering experience\nKnowledge of assembly processes and lean principles\nComfortable working between R&D and the shop floor\nFluent English in speech and writing; Swedish is a strong plus\nBased in or able to commute to the Gothenburg area",
  "nice_to_have": "",
  "is_open": true
 },
 {
  "title": "Tax Strategy & Policy Lead",
  "department": "Finance",
  "type": "Full-time",
  "location": "Gothenburg",
  "salary": "",
  "summary": "Shape group tax strategy and policy — advising the business and keeping a multinational structure compliant and efficient.",
  "responsibilities": "Develop and maintain group tax strategy and policies\nAdvise business units on tax implications of decisions\nMonitor international tax developments and assess impact\nCoordinate with external advisors and authorities",
  "requirements": "Deep corporate tax expertise, ideally in a multinational group\nExperience with transfer pricing and international tax law\nStrong advisory and stakeholder skills\nFluent English in speech and writing; Swedish is a strong plus\nBased in or able to commute to the Gothenburg area",
  "nice_to_have": "",
  "is_open": true
 },
 {
  "title": "Test Engineer (Experienced)",
  "department": "Testing & Verification",
  "type": "Full-time",
  "location": "Gothenburg",
  "salary": "",
  "summary": "Plan and execute tests that prove product quality — writing test cases, running them and turning results into clear findings.",
  "responsibilities": "Design test cases from requirements\nExecute tests in lab, rig or vehicle environments\nAnalyse and document results, report defects\nImprove test methods and coverage",
  "requirements": "2–4 years of relevant experience\nTesting experience in automotive or embedded products\nFamiliar with test management and defect tracking tools\nAnalytical and thorough with good documentation habits\nFluent English in speech and writing; Swedish is a strong plus\nBased in or able to commute to the Gothenburg area",
  "nice_to_have": "",
  "is_open": true
 },
 {
  "title": "Hardware Verification Engineer (Senior)",
  "department": "Testing & Verification",
  "type": "Full-time",
  "location": "Gothenburg",
  "salary": "",
  "summary": "Verify electronic hardware against requirements — planning and running the environmental, electrical and functional tests.",
  "responsibilities": "Plan hardware verification per requirements and standards\nRun electrical, environmental and durability tests\nAnalyse failures and support root-cause work\nWrite verification reports",
  "requirements": "5–8 years of relevant experience\nHardware verification or E/E testing experience\nFamiliar with lab instrumentation and test standards\nAutomotive EMC or environmental testing is a plus\nFluent English in speech and writing; Swedish is a strong plus\nBased in or able to commute to the Gothenburg area",
  "nice_to_have": "",
  "is_open": true
 },
 {
  "title": "Business Solution Engineer (Senior Expert)",
  "department": "Software & IT",
  "type": "Full-time",
  "location": "Gothenburg",
  "salary": "",
  "summary": "Bridge business needs and IT solutions — analysing processes, shaping solutions and guiding implementations.",
  "responsibilities": "Analyse business processes and translate needs into IT solutions\nConfigure and improve business applications\nDrive solution design with architects and vendors\nSupport rollout, training and adoption",
  "requirements": "8+ years of deep experience in the field\nExperience as business analyst or solution engineer\nUnderstanding of enterprise applications and integrations\nStrong workshop, documentation and communication skills\nFluent English in speech and writing; Swedish is a strong plus\nBased in or able to commute to the Gothenburg area",
  "nice_to_have": "",
  "is_open": true
 },
 {
  "title": "Manufacturing Engineer",
  "department": "Engineering",
  "type": "Full-time",
  "location": "Gothenburg",
  "salary": "",
  "summary": "Develop and improve manufacturing processes — equipment, methods and flows that make production efficient and stable.",
  "responsibilities": "Develop and optimise manufacturing processes and equipment\nDrive improvement projects on quality, cost and delivery\nSupport production with technical problem solving\nMaintain process documentation and standards",
  "requirements": "3–5 years of relevant experience\nManufacturing engineering experience\nKnowledge of lean production and process improvement\nHands-on and analytical at the same time\nFluent English in speech and writing; Swedish is a strong plus\nBased in or able to commute to the Gothenburg area",
  "nice_to_have": "",
  "is_open": true
 },
 {
  "title": "Maintenance Engineer",
  "department": "Engineering",
  "type": "Full-time",
  "location": "Gothenburg",
  "salary": "",
  "summary": "Keep production equipment reliable and available — preventive maintenance, improvements and technical support to operations.",
  "responsibilities": "Develop and maintain preventive maintenance programs\nAnalyse equipment performance and reduce recurring downtime\nSupport operations with technical troubleshooting\nManage spare parts and maintenance documentation",
  "requirements": "3–5 years of relevant experience\nExperience in industrial maintenance engineering\nGood knowledge of maintenance processes and systems\nPractical, structured and improvement-driven\nFluent English in speech and writing; Swedish is a strong plus\nBased in or able to commute to the Gothenburg area",
  "nice_to_have": "",
  "is_open": true
 },
 {
  "title": "Adaptation Engineer (Junior)",
  "department": "Engineering",
  "type": "Full-time",
  "location": "Gothenburg",
  "salary": "",
  "summary": "Adapt vehicle configurations to specific customer needs — turning special requirements into buildable, documented solutions.",
  "responsibilities": "Analyse customer-specific requirements on vehicle configuration\nDesign and document adaptations within product rules\nCoordinate with engineering, sales and production\nMaintain adaptation documentation and lessons learned",
  "requirements": "0–2 years of relevant experience — recent graduates are welcome\nEngineering background, ideally in vehicle or industrial products\nStructured with a strong sense for documentation\nEnjoys the mix of technology and customer contact\nFluent English in speech and writing; Swedish is a strong plus\nBased in or able to commute to the Gothenburg area",
  "nice_to_have": "",
  "is_open": true
 },
 {
  "title": "Business Controller / Financial Analyst",
  "department": "Finance",
  "type": "Full-time",
  "location": "Gothenburg",
  "salary": "",
  "summary": "Turn numbers into decisions — budgeting, forecasting and business analysis for operational and senior stakeholders.",
  "responsibilities": "Own budgeting, forecasting and monthly follow-up\nAnalyse deviations and business performance\nBuild reports and dashboards for management\nAct as finance partner to the business",
  "requirements": "3–5 years of relevant experience\nDegree in finance/economics with controlling experience\nStrong Excel and reporting-tool skills\nProactive, analytical and business-oriented\nFluent English in speech and writing; Swedish is a strong plus\nBased in or able to commute to the Gothenburg area",
  "nice_to_have": "",
  "is_open": true
 },
 {
  "title": "Test Engineer (Specialist)",
  "department": "Testing & Verification",
  "type": "Full-time",
  "location": "Gothenburg",
  "salary": "",
  "summary": "Plan and execute tests that prove product quality — writing test cases, running them and turning results into clear findings.",
  "responsibilities": "Design test cases from requirements\nExecute tests in lab, rig or vehicle environments\nAnalyse and document results, report defects\nImprove test methods and coverage",
  "requirements": "5+ years of relevant experience in the field\nTesting experience in automotive or embedded products\nFamiliar with test management and defect tracking tools\nAnalytical and thorough with good documentation habits\nFluent English in speech and writing; Swedish is a strong plus\nBased in or able to commute to the Gothenburg area",
  "nice_to_have": "",
  "is_open": true
 },
 {
  "title": "Test Engineer (Senior)",
  "department": "Testing & Verification",
  "type": "Full-time",
  "location": "Gothenburg",
  "salary": "",
  "summary": "Plan and execute tests that prove product quality — writing test cases, running them and turning results into clear findings.",
  "responsibilities": "Design test cases from requirements\nExecute tests in lab, rig or vehicle environments\nAnalyse and document results, report defects\nImprove test methods and coverage",
  "requirements": "5–8 years of relevant experience\nTesting experience in automotive or embedded products\nFamiliar with test management and defect tracking tools\nAnalytical and thorough with good documentation habits\nFluent English in speech and writing; Swedish is a strong plus\nBased in or able to commute to the Gothenburg area",
  "nice_to_have": "",
  "is_open": true
 },
 {
  "title": "Operational Buyer",
  "department": "Purchasing",
  "type": "Full-time",
  "location": "Gothenburg",
  "salary": "",
  "summary": "Keep the supply flowing — purchase orders, delivery follow-up and daily supplier contact for production needs.",
  "responsibilities": "Place and follow up purchase orders toward suppliers\nSecure deliveries and resolve shortages\nMaintain purchasing data in ERP systems\nSupport supplier performance follow-up",
  "requirements": "1–3 years of relevant experience\nExperience in operational purchasing or supply chain\nComfortable in ERP systems and structured follow-up\nService-minded with clear communication\nFluent English in speech and writing; Swedish is a strong plus\nBased in or able to commute to the Gothenburg area",
  "nice_to_have": "",
  "is_open": true
 },
 {
  "title": "Adaptation Engineer (Lead)",
  "department": "Engineering",
  "type": "Full-time",
  "location": "Gothenburg",
  "salary": "",
  "summary": "Adapt vehicle configurations to specific customer needs — turning special requirements into buildable, documented solutions.",
  "responsibilities": "Analyse customer-specific requirements on vehicle configuration\nDesign and document adaptations within product rules\nCoordinate with engineering, sales and production\nMaintain adaptation documentation and lessons learned",
  "requirements": "8+ years of experience, including leading teams or workstreams\nEngineering background, ideally in vehicle or industrial products\nStructured with a strong sense for documentation\nEnjoys the mix of technology and customer contact\nFluent English in speech and writing; Swedish is a strong plus\nBased in or able to commute to the Gothenburg area",
  "nice_to_have": "",
  "is_open": true
 },
 {
  "title": "Technical Customer Support Specialist",
  "department": "Management & Ops",
  "type": "Full-time",
  "location": "Gothenburg",
  "salary": "",
  "summary": "Help dealers and customers solve technical problems — troubleshooting, guidance and escalations for products in the field.",
  "responsibilities": "Handle technical support cases from dealers and markets\nTroubleshoot issues and guide repairs remotely\nEscalate product issues to engineering with clear data\nContribute to knowledge base and service information",
  "requirements": "3–5 years of relevant experience\nTechnical background in vehicles or industrial equipment\nExperience in technical support or aftermarket\nPedagogical, patient and solution-focused\nFluent English in speech and writing; Swedish is a strong plus\nBased in or able to commute to the Gothenburg area",
  "nice_to_have": "",
  "is_open": true
 },
 {
  "title": "Business Consultant (Senior)",
  "department": "Software & IT",
  "type": "Full-time",
  "location": "Gothenburg",
  "salary": "",
  "summary": "Advise organisations on process and IT improvement — analysing, recommending and driving change side by side with the client.",
  "responsibilities": "Analyse client processes, systems and ways of working\nDevelop improvement recommendations and business cases\nDrive implementation together with client teams\nFacilitate workshops and stakeholder alignment",
  "requirements": "5–8 years of relevant experience\nConsulting or business development experience\nStrong analytical and presentation skills\nComfortable owning client relationships\nFluent English in speech and writing; Swedish is a strong plus\nBased in or able to commute to the Gothenburg area",
  "nice_to_have": "",
  "is_open": true
 },
 {
  "title": "Service Designer (Senior Expert)",
  "department": "Design",
  "type": "Full-time",
  "location": "Gothenburg",
  "salary": "",
  "summary": "Design services end-to-end — mapping customer journeys, spotting friction and shaping better experiences across touchpoints.",
  "responsibilities": "Map customer journeys and service blueprints\nRun user research and co-creation workshops\nDesign improved service concepts and prototypes\nWork with product and business teams on implementation",
  "requirements": "8+ years of deep experience in the field\nStrong service design portfolio and methods toolkit\nExperienced facilitator and researcher\nSystems thinker with strong storytelling skills\nFluent English in speech and writing; Swedish is a strong plus\nBased in or able to commute to the Gothenburg area",
  "nice_to_have": "",
  "is_open": true
 },
 {
  "title": "Embedded Software Application Engineer (Expert)",
  "department": "Software & IT",
  "type": "Full-time",
  "location": "Gothenburg",
  "salary": "",
  "summary": "Develop embedded application software for vehicle functions — from requirements to tested code running in the ECU.",
  "responsibilities": "Design and implement embedded application software in C/C++\nWork with function owners on requirements and behaviour\nTest and debug software in SIL/HIL environments and vehicles\nContribute to code reviews and continuous improvement",
  "requirements": "8+ years of deep experience in the field\nEmbedded C/C++ development experience\nUnderstanding of automotive software architectures (e.g. AUTOSAR)\nExperience with embedded toolchains and debugging\nFluent English in speech and writing; Swedish is a strong plus\nBased in or able to commute to the Gothenburg area",
  "nice_to_have": "",
  "is_open": true
 },
 {
  "title": "Packaging Engineer (Senior)",
  "department": "Engineering",
  "type": "Full-time",
  "location": "Gothenburg",
  "salary": "",
  "summary": "Develop packaging solutions that protect parts and optimise logistics — from design and testing to supplier follow-up.",
  "responsibilities": "Design packaging solutions for parts and components\nBalance protection, cost, ergonomics and sustainability\nTest and validate packaging designs\nWork with suppliers and logistics on implementation",
  "requirements": "5–8 years of relevant experience\nPackaging or logistics engineering experience\nKnowledge of packaging materials and standards\nCAD skills are a plus\nFluent English in speech and writing; Swedish is a strong plus\nBased in or able to commute to the Gothenburg area",
  "nice_to_have": "",
  "is_open": true
 },
 {
  "title": "Marketing Manager (Senior)",
  "department": "Management & Ops",
  "type": "Full-time",
  "location": "Gothenburg",
  "salary": "",
  "summary": "Drive marketing strategy and campaigns — positioning, content and channels that build the brand and generate demand.",
  "responsibilities": "Develop marketing plans, campaigns and content\nManage channels, agencies and budgets\nTrack campaign performance and optimise\nAlign marketing with sales and product teams",
  "requirements": "5–8 years of relevant experience\nSeveral years of B2B marketing experience\nStrong project management and copy sense\nDigital channel and analytics competence\nFluent English in speech and writing; Swedish is a strong plus\nBased in or able to commute to the Gothenburg area",
  "nice_to_have": "",
  "is_open": true
 },
 {
  "title": "Logistics Engineer",
  "department": "Engineering",
  "type": "Full-time",
  "location": "Gothenburg",
  "salary": "",
  "summary": "Design efficient material flows — from goods receiving to line feeding — and drive logistics improvements in production.",
  "responsibilities": "Design and improve internal material flows and layouts\nSet logistics parameters and packaging instructions\nDrive improvement projects with production and suppliers\nSupport new product introductions from a logistics view",
  "requirements": "3–5 years of relevant experience\nLogistics or supply chain engineering experience\nKnowledge of lean logistics and material handling\nAnalytical with good system skills (ERP/WMS)\nFluent English in speech and writing; Swedish is a strong plus\nBased in or able to commute to the Gothenburg area",
  "nice_to_have": "",
  "is_open": true
 },
 {
  "title": "Accounting Administrator",
  "department": "Finance",
  "type": "Full-time",
  "location": "Gothenburg",
  "salary": "",
  "summary": "Keep the books accurate and on time — ledger work, reconciliations and support in monthly closing.",
  "responsibilities": "Handle accounts payable/receivable and ledger entries\nPerform reconciliations and support monthly closing\nMaintain accounting documentation and routines\nSupport audits with documentation",
  "requirements": "3–5 years of relevant experience\nExperience in accounting or finance administration\nAccurate, structured and deadline-oriented\nComfortable in ERP/accounting systems\nFluent English in speech and writing; Swedish is a strong plus\nBased in or able to commute to the Gothenburg area",
  "nice_to_have": "",
  "is_open": true
 },
 {
  "title": "Learning & Development Lead",
  "department": "Management & Ops",
  "type": "Full-time",
  "location": "Gothenburg",
  "salary": "",
  "summary": "Lead training delivery for a global organisation — planning, coordinating and improving how people learn.",
  "responsibilities": "Plan and coordinate training programs and sessions\nManage trainers, venues and learning platforms\nMeasure training effectiveness and improve content\nSupport rollout of new learning initiatives",
  "requirements": "Experience in L&D delivery or training coordination\nStrong organisational and facilitation skills\nFamiliar with LMS platforms\nFluent English in speech and writing; Swedish is a strong plus\nBased in or able to commute to the Gothenburg area",
  "nice_to_have": "",
  "is_open": true
 }
];
